use_frameworks!

target 'RxSwiftStudy' do
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxDataSources'
    pod 'RxAlamofire'
    pod 'ObjectMapper'
    pod 'Moya'
    pod 'Moya/RxSwift'
    pod 'HandyJSON'
    pod 'MJRefresh'
    pod ‘Kingfisher’
    pod 'IQKeyboardManagerSwift'
end